### ISSUE TITLE
add methylation, coverage matrix functionality to cmapPy

### ISSUE THREAD

**Issue by bsiranosian** [Cellular-Longevity/cmapPy#1]

**Comment by DavidTingley** [comment]
Are there any other 2D data matrices that would not fall under metadata (i.e. a single row or column that aligns with a sample or CpG site)?

secondary part of this, get cmapPy working in python3

**Comment by bsiranosian** [comment]
Initial implementation in 2fc3806b5eaa867399fae17fb7a3c3d5de58df45
