### ISSUE TITLE
formalize data formatting/objects for methylation+metadata

### ISSUE THREAD

**Issue by DavidTingley** [Cellular-Longevity/cmapPy#3]

**Comment by bsiranosian** [comment]
Can you add some description to this if it's still necessary after the modifications?

**Comment by DavidTingley** [comment]
![image](https://user-images.githubusercontent.com/5696262/158785374-6cd3746a-4ec0-4253-92ca-10c6b755853f.png)
Still getting issues like this, where the HDF5 datasets are named slightly differently, parse_gctx.py goes looking for 'matrix' rather than methylation_matrix and coverage_matrix. Do we have a naming standard going forward? 

Do we ever anticipate a 3rd (or Nth) matrix we'd want to add to these files? If so I can start coding this up to take HDF5 files with an arbitrary number of /DATA/ matrices. It seems this would break with standard *.gctx format significantly 
![image](https://user-images.githubusercontent.com/5696262/158786076-8d4c64b5-5726-4d6f-bd11-7934f5cb7c6b.png)

**Comment by DavidTingley** [comment]
It might also be a little sketchy to assume the ordering of coverage/methylation matrices without a check (someone will eventually put these in the wrong order). If we split `data_node = "/0/DATA/0/matrix"` into different 2D datasets as above, we can carry through their names to avoid potential mix ups. What do you think? 


![image](https://user-images.githubusercontent.com/5696262/158789999-fadb30b7-6b06-492b-a1b8-7af8885eb029.png)
![image](https://user-images.githubusercontent.com/5696262/158790032-10deac9b-2518-4348-ae1f-e2286ba2a966.png)

**Comment by DavidTingley** [comment]
Leave the formatting as is, close this when assert check added for the matrix ordering (coverage/methylation)

**Comment by DavidTingley** [comment]
057e770e74db58c37b1d9155030ad4d0fe7b7e75 resolves this for now
