### ISSUE TITLE
parse error with internal s3 *.gctx files

### ISSUE THREAD

**Issue by DavidTingley** [Cellular-Longevity/cmapPy#6]
![image](https://user-images.githubusercontent.com/5696262/158371895-e0270d70-4e14-4c8d-82ba-f303bd6d39e4.png)
 
I'm only getting this error with GCTX files we have generated, the same code on external files seems to return OK. Parse with the `col_meta_only` or `row_meta_only` flags returns the row/col metadata without an error so it looks to only be an issue w/ methylation data matrix
 
 Any ideas?

**Comment by DavidTingley** [comment]
failed on:
'processed_methylation_data/HEALTHSPAN/ADMERA_100/matrices_processed/methylation_filtered.gctx' 'processed_methylation_data/combined_datasets/all_saliva/matrices_processed/methylation_filtered.gctx_n98x997979.gctx'

but has worked on:
https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE70138&format=file&file=GSE70138%5FBroad%5FLINCS%5Fsig%5Finfo%5F2017%2D03%2D06%2Etxt%2Egz

**Comment by bsiranosian** [comment]
This is expected given that I'm writing modified, technically invalid gctx files from the R implementation. If you inspect the file: 
```
h5ls -r ~/loyal_local/data/processed_methylation_data/HEALTHSPAN/ADMERA_100/processed_gctx/methylation_filtered.gctx 
/                        Group
/0                       Group
/0/DATA                  Group
/0/DATA/0                Group
/0/DATA/0/coverage_matrix Dataset {83, 2226661}
/0/DATA/0/methylation_matrix Dataset {83, 2226661}
...
```
you can see there are two data matrices, where the python implementation expects a single data matrix at the address `/0/DATA/0/matrix`

So this won't be resolved until the code is modified to account for additional dimensions - I'm looking at multiindexed dataframes for this now.

**Comment by DavidTingley** [comment]
It looks like in parse_gctx.py that inspecting the file and iterating over data nodes, rather than hard coding, could be a solution. Output could be a list of dataframes, or multi-indexed with the node name 
![image](https://user-images.githubusercontent.com/5696262/158381321-7e57c335-9612-40ff-86f3-8b6cadeaaea0.png)

**Comment by bsiranosian** [comment]
I actually think keeping the address at matrix, and using a higher dimension is going to be the best solution for consistency and portability. Then we just have to answer how the data is addressed within the tool. 

Right now, in R I use 
```
mgct@meth_mat
mgct@cov_mat
``` 
to access the methylation and coverage matrices separately. If `mat` is just a higher dimension array with the final dimension being meth/coverage, that becomes
```
mgct@mat[,,1]
mgct@mat[,,2]
```
which is slightly less convenient, and you always have to remember you're dealing with a 3D object. So maybe it's best to expose two 2D objects within the package, but keep the reading/writing operations as 3D?

**Comment by bsiranosian** [comment]
This should be working as of 2fc3806b5eaa867399fae17fb7a3c3d5de58df45

Note that internal gctx files will have to be re-generated to use the 3D array in the hdf5 file, so they will be broken for now.
