### ISSUE TITLE
Graceful behavior when loading a unmodified gctx

### ISSUE THREAD

**Issue by bsiranosian** [Cellular-Longevity/cmapPy#7]
This is fixed in R, TBD in python. 

When loading a gctx file that was created with the traditional version of the cmapR or cmapPy package, it should load the data into the meth_mat slot, and put a matrix of NAs in the cov_mat slot.

This is important because I use the same format for processing kraken2 results with the code from https://github.com/bhattlab/kraken2_classification

see https://github.com/Cellular-Longevity/cmapR/issues/3

**Comment by DavidTingley** [comment]
Is there a traditional *.gctx file you could point me to on S3 and I'll check this?

**Comment by bsiranosian** [comment]
I use it for taxonomic classification matrices for oral microbiome content, for example. 
`s3://bioinformatics-loyal/nf-core_processing/HEALTHSPAN/ADMERA_100_ALL/kraken2_classification/standard_custom_bisulfite/taxonomy_gctx_classified_only/kraken_species_percentage.gctx`
